# role-arca-deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: arca
  name: jenkins-deployment-role
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "services"]
  verbs: ["get", "list", "create", "update", "delete"]